CANCUN: EIP-1153 Transient Storage
ethereum/yellowpaper pull request #916
Opened 2024-08-26 15:04 UTC by pldespaigne

# EIP 1153 Transient Storage
> This is the first PR aiming to bring the Yellow Paper up to date with Cancun update

This PR translate [EIP-1553](https://eips.ethereum.org/EIPS/eip-1153) into the Yellow Paper.

## Definition
We formally define the Transient Storage as $\boldsymbol{\theta}$ (symbol not already used in the paper), in section 6. Transaction Execution.

<details>
<summary>Screenshot</summary>

![0_after](https://github.com/user-attachments/assets/6589e684-5d70-4d5e-aaa4-b280c82f601e)

</details>

## Updating functions $\Theta$, $\Lambda$ and $\Xi$
We updated every occurrence of the **Message Call** function $\boldsymbol{\Theta}$ to incorporate transient storage $\boldsymbol{\theta}$ as the second parameter and new resultant transient storage $\boldsymbol{\theta}'$ as the last returned parameter.

<details>
<summary>Screenshot</summary>

![3_after](https://github.com/user-attachments/assets/5163eca8-71f9-4a22-b101-872dd324e8ba)

</details>

We updated every occurrence of the **Create** function $\boldsymbol{\Lambda}$ to incorporate transient storage $\boldsymbol{\theta}$ as the second parameter and new resultant transient storage $\boldsymbol{\theta}'$ as the last returned parameter.

<details>
<summary>Screenshot</summary>

![2_after](https://github.com/user-attachments/assets/ce9dba42-71b2-4833-9398-764800fb890a)

</details>

We updated every occurrence of the **Execution** function $\boldsymbol{\Xi}$ to incorporate transient storage $\boldsymbol{\theta}$ as the second parameter and new resultant transient storage $\boldsymbol{\theta}'$ as the second returned parameter.

<details>
<summary>Screenshot</summary>

![4_after](https://github.com/user-attachments/assets/cdc7d2c0-2c54-412d-8037-8b17b865fddd)

</details>

## STATICCALL Exception
We added $\small{TSTORE}$ to the list of forbidden opocodes during a static execution.

<details>
<summary>Screenshot</summary>

![5_after](https://github.com/user-attachments/assets/28aba66b-c59f-450d-8565-a508c4b99263)

</details>

## Gas cost
We added $\small{TLOAD}$ and $\small{TSTORE}$ to gas opcode categories.

<details>
<summary>Screenshot</summary>

![8_after](https://github.com/user-attachments/assets/bbf6e085-cfa9-4c66-8145-c40d66bf7137)

</details>

We added a new fee tier for that category.

<details>
<summary>Screenshot</summary>

![6_after](https://github.com/user-attachments/assets/d859efac-a820-42d0-a839-889c2cdbc154)

</details>

Finally, we updated the gas cost function $C$ to handle those new opcodes.

<details>
<summary>Screenshot</summary>

![7_after](https://github.com/user-attachments/assets/386d0b31-f63f-4e46-a867-c56f676953f3)

</details>

## Opcodes Definition
We added $\small{TLOAD}$ and $\small{TSTORE}$ to the list of opcodes.

<details>
<summary>Screenshot</summary>

![9_after](https://github.com/user-attachments/assets/2f134842-b9af-458d-9839-5acc61a3805f)

</details>

2024-08-26 15:05 UTC, pldespaigne commented
@yperbasis could you create a `cancun` branch please, so that I can update the target branch of the PR and mark it as ready to review 🙏

2024-08-27 07:49 UTC, yperbasis commented
> @yperbasis could you create a `cancun` branch please, so that I can update the target branch of the PR and mark it as ready to review 🙏

done

2024-08-27 08:09 UTC, pldespaigne commented
Thanks!
PR is now ready to review!

@alexprut @benjaminion @RenanSouza2 @timbeiko @alexkroeger any feedback on that will be highly appreciated as well 🙏

2024-08-29 11:42 UTC, RenanSouza2 commented
Hey, I‘m not sure why I was mentionend but I have two suggestions, 

the first one is to simplify the section 6.2 to
'The transient storage (eip1153), fomrally ...‘

the second one is to use Gwarmaccess in the gas formula instead of creating a new category

2024-08-29 18:07 UTC, pldespaigne commented
Thanks for your feedback!

What needs to be simplified in section 6.2 for you? would you avoid to formally define the transient storage and simply says that it behave almost as the regular storage, like the EIP-1153 does?

I did it this way so it's more future proof if one of those gas category change, but yeah it doesn't look clean, and I think I like it better using only $G_{warmaccess}$.

2024-08-29 21:16 UTC, RenanSouza2 commented
I have one more suggestion, to move the definition from section 6 (transaction execution) to section 9 (Execution model),

this could be integrated in 9.1 (basics), or there could be a revamp and expand the explanation of memory, storage, 



my previous suggestion was to remove the sentences 'introduced by eip 1153, during the cancun update' and start by 'the transient storage (eip1153)[authors], formally ...'

2024-08-30 14:49 UTC, pldespaigne commented
From what I understand, section 9 describe thing relative to a single execution context (such as memory, environment, etc...).

Structures used for the whole transaction (such as accrued sub-state) are defined in section 6.

Since transient storage is created at the beginning of the tx (and destroy at the end) and persist across contexts, I find it more logical to put it in section 6.
Again that's just my opinion, I'm happy to discuss this further and make that update if everybody agrees on it.

2024-08-31 14:18 UTC, RenanSouza2 commented
makes sense, 6.1 is substate and 6.2 is transient storage

2024-10-02 15:57 UTC, alexprut commented on Paper.tex
> +It's a mapping between addresses (160-bit identifiers) and storage (another mapping between 256-bit integer values).
Maybe adding: `bi-dimentional` mapping?

No strong opinions, up to you.

2024-10-02 16:00 UTC, alexprut commented on Paper.tex
> +It's a mapping between addresses (160-bit identifiers) and storage (another mapping between 256-bit integer values).
The definition of an address is already defined in multiple places, such as formula `(97)`, for simplicity maybe the piece `(160-bit identifiers)` could be removed.

2024-10-02 16:01 UTC, alexprut commented on Paper.tex
> +a \in \mathbb{B}_{160} \quad \wedge \quad k \in \mathbb{B}_{32} \quad \wedge \quad v \in \mathbb{N}
Same here, `a \in \mathbb{B}_{160}` could be moved to formula `(97)`

2025-01-16 15:56 UTC, pldespaigne commented on Paper.tex
> +a \in \mathbb{B}_{160} \quad \wedge \quad k \in \mathbb{B}_{32} \quad \wedge \quad v \in \mathbb{N}
I prefer to leave it there to make the definition more standalone

2025-01-16 16:01 UTC, pldespaigne commented
As suggested by @RenanSouza2 & @alexprut, I've updated the definition paragraph of the Transient storage.

![image](https://github.com/user-attachments/assets/ac6bff09-d11a-4438-b12b-c16eecf17152)

@yperbasis Could you have a look when you have some time please, and if everything is ok for you, merge into `cancun` branch, so that I can start the next EIP 🙏

2025-01-20 10:05 UTC, pldespaigne commented
Tagging EIP authors to help review if they want/can 🙏
@AlexeyAkhunov, @moodysalem

2025-01-20 13:46 UTC, moodysalem commented
If mentioning that it's cheaper because it never has to be persisted, I might also add that it's cheaper because it never has to _read from_ the storage trie either since all slots start at zero. Otherwise, looks good!

2025-02-14 07:13 UTC, pldespaigne commented
@yperbasis If everything is fine for you, could you merge to the `cancun` branch so I can move to the next EIP?

2025-02-17 13:35 UTC, yperbasis requested changes
Please make the following changes:

1. In some functions theta is the last return parameter and in others it's the second return parameters. Please make it consistent (probably the second return place is better so that it follows sigma).
2. The cost should be defined as G_warmaccess, not independently, since that's how the EIP defines it.

2025-02-21 08:32 UTC, pldespaigne commented
Hey @yperbasis!
Thanks a lot for your time reviewing my PR!

I totally agree with the requested changes, however it it require to update this part of YP as well (section 6.3.)
What do you think?
![image](https://github.com/user-attachments/assets/77254590-7e53-4c7c-a6ec-0fda96f24305)

2025-02-21 10:38 UTC, yperbasis commented
@pldespaigne Ah, I see. Then it makes sense to have theta as the last output. But then I'd make it the last output of Xi as well for consistency.

2025-02-23 10:03 UTC, pldespaigne commented
@yperbasis done!
Everything should be ok now

2025-02-25 11:08 UTC, yperbasis commented on Paper.tex
> +Note we use $\hyperlink{theta}{\Theta}_{4}$ and $\hyperlink{lambda}{\Lambda}_{4}$ to denote the fact that only the first four components of the functions' values are taken; the finals represents the
typo: "finals represents"

2025-02-25 11:15 UTC, yperbasis reviewed
LGTM except for the small "finals represents" typo

2025-02-26 09:37 UTC, pldespaigne commented
Done!
Could you merge it into the `cancun` branch please 🙏
I'll now move on to EIP-4844

2025-02-26 11:00 UTC, yperbasis approved these changes

2025-02-26 11:00 UTC, merged